### PR TITLE
fix for `tmp_travis_folder` path in composer.json

### PR DESCRIPTION
**Pull request by damianz5**

### CODE REVIEW

**Comment by damianz5** [comment]
ping @andrerom

**Comment by lserwatka** [comment]
@andrerom shouldn't we merge this to upstream ezplatform and then pull here?

**Comment by andrerom** [comment]
Yes

**Comment by lserwatka** [comment]
@damianz5 can you please close this PR and open it against ezplatform meta repo?

**Comment by andrerom** [comment]
@lserwatka But with the product name change the studio script can just as well clone the meta repo into ezplatform folder!

**Comment by andrerom** [comment]
see proposed changes in https://github.com/ezsystems/StudioUIBundle/pull/654 instead.

**Comment by lserwatka** [comment]
@andrerom that should work too, we will test it

**Comment by micszo** [comment]
@andrerom The applied changes in StudioUI cover the first part of this PR. What about the second part related to composer.json? That is still failing.

**Comment by andrerom** [comment]
the other change is I guess ok even if I'm unsure what `repositories.tmp_travis_folde` means here.
But this change should then go to ezplatform and be merged up to ezstudio / ezplatform-ee once approved.

**Comment by damianz5** [comment]
I will create the same changes for ezplatform and we can close this PR.

adding new repository url at the end of composer.json file for ezstudio is causing error
`Key repositories is a duplicate in ./composer.json at line 103` because there is already one entry with 'repository' key - url for updates.ez.no, and this is not just a notice - composer will read only last key.

Which solution will be better:
`composer config repositories.tmp_travis_folder git ${HOME}/build/ezplatform/tmp_travis_folder
 `
or 
```
sed -i '$d' composer.json
 -echo ',    "repositories": [{ "type": "composer", "url": "https://updates.ez.no/ttl"},{"type":"git","url":"'${HOME}'/build/ezplatform/tmp_travis_folder"}]}' >> composer.json
```

there are two additional issues:
1. [this line](http://github.com/damianz5/ezstudio/blob/master/bin/.travis/trusty/setup_from_external_repo.sh#L46) broke the studioUI build, auth.json exists already
2. at least for StudioUI we should install `demo`, not `clean` at [this line](http://github.com/ezsystems/ezstudio/blob/master/bin/.travis/trusty/setup_from_external_repo.sh#L69)

**Comment by damianz5** [comment]
This PR has been closed in favor of https://github.com/ezsystems/ezplatform/pull/152

**Pull request closed without merging**
